### ISSUE TITLE
How to use angular softmax loss

### ISSUE THREAD

**Issue by rameshkunasi** [mycrazycracy/tf-kaldi-speaker#12]
Hi,

Can you please give a brief idea about how to configure angular softmax as a loss function in the script?

Training steps I am not able to understand

**Comment by rameshkunasi** [comment]
I understood the procedure to run. But while running I am getting **Could not find enough idle GPUs** error. How to resolve this issue

**Comment by mycrazycracy** [comment]
Hi,

First, make sure your tensorflow can find your gpu (launch python and follow the steps in tf website).

Then, check utils/parallel/limit_num_gpus.sh and you can find which step it fails.

As to the asoftmax, find the corresponding config file in nnet_conf/ to see whether you can understand the configuration.

**Comment by rameshkunasi** [comment]
@mycrazycracy , 

I have installed tensorflow-gpu==1.12 and verified whether tensorflow able to detect gpu or not, it detected properly.

I am using single gpu for training. In utils/parallel/limit_num_gpus.sh num_gpus_assigned=0 so it is failing in that step. 
why the gpu should be idle? i am running another training script in the same gpu, will it be problem?

**Comment by rameshkunasi** [comment]
I am using python3.6 
below error occuring in the log file after resolving GPU issue

**File "/root/data_common3tb/Ramesh/tf-kaldi-speaker/dataset/data_loader.py", line 291, in batch_random
    rd.jumpahead(seed)
AttributeError: 'Random' object has no attribute 'jumpahead'**

**Comment by mycrazycracy** [comment]
Yes, in python3, jumpahead is removed. Please refer to https://github.com/mycrazycracy/tf-kaldi-speaker/issues/10 <https://github.com/mycrazycracy/tf-kaldi-speaker/issues/10>

**Comment by mycrazycracy** [comment]
If you want to run several programs in a single GPU, change the script for yourself please.

**Comment by mycrazycracy** [comment]
BTW, I have some copyright problems currently. Would set the repository private temporarily.
