### ISSUE TITLE
Inference script

### ISSUE THREAD

**Issue by shatealaboxiaowang** [mycrazycracy/tf-kaldi-speaker#6]
Hi Dr.Liu:
     Thank you very much for your sharing, I have  seen your eer result(eer=0.02) is state of the art, but i have a few question for you. (1) I don't see the predict code, i just want to try the inference ; (2)How many days did you train on the voxceleb dataset?
     Looking forward to your reply. Thank you!!

**Comment by mycrazycracy** [comment]
Hi,
(1) I must point out that EER=2% is achieved when the VoxCeleb2 and VoxCeleb1 dev set is used to train the model. In the official protocol, only the VoxCeleb2 dev set can be used. So currently I have no idea about the performance if only the VoxCeleb2 dev set is used.
(2) The inference code is included in the script. Take a look at egs/voxceleb/v1/run.sh and you can search nnet/run_extract_embeddings.sh which extracts the speaker embedding.
(3) I used a single P100 GPU and the training takes about 2.5 days (178031s exactly). Some methods can be involved to accelerate the training process but I didn't do that.

If you have any other questions, please let me know.

**Comment by shatealaboxiaowang** [comment]
Thank you very much，I will try it and consult you when I encounter problems 。
